:rotating_light: Convert to address type
Fixes TypeScript type issues returned by the command:
```
deno check utils.ts
```
The error were:
```
Check file:///berachain-experiments/utils.ts
TS2322 [ERROR]: Type 'string' is not assignable to type '`0x${string}`'.
      address: tokenAddress,
      ~~~~~~~
    at file:///berachain-experiments/utils.ts:37:7

    The expected type comes from property 'address' which is declared here on type 'ReadContractParameters<readonly [{ readonly type: "event"; readonly name: "Approval"; readonly inputs: readonly [{ readonly indexed: true; readonly name: "owner"; readonly type: "address"; }, { readonly indexed: true; readonly name: "spender"; readonly type: "address"; }, { ...; }]; }, ... 9 more ..., { ...; }], "ba...'
        address: Address;
        ~~~~~~~
        at file:///.cache/deno/npm/registry.npmjs.org/viem/2.22.16/_types/types/contract.d.ts:41:5

TS2322 [ERROR]: Type 'string' is not assignable to type '`0x${string}`'.
      args: [accountAddress],
             ~~~~~~~~~~~~~~
    at file:///berachain-experiments/utils.ts:40:14

TS2322 [ERROR]: Type 'string' is not assignable to type '`0x${string}`'.
      address: tokenAddress,
      ~~~~~~~
    at file:///berachain-experiments/utils.ts:43:7

    The expected type comes from property 'address' which is declared here on type 'ReadContractParameters<readonly [{ readonly type: "event"; readonly name: "Approval"; readonly inputs: readonly [{ readonly indexed: true; readonly name: "owner"; readonly type: "address"; }, { readonly indexed: true; readonly name: "spender"; readonly type: "address"; }, { ...; }]; }, ... 9 more ..., { ...; }], "de...'
        address: Address;
        ~~~~~~~
        at file:///.cache/deno/npm/registry.npmjs.org/viem/2.22.16/_types/types/contract.d.ts:41:5

TS2322 [ERROR]: Type 'string' is not assignable to type '`0x${string}`'.
      address: tokenAddress,
      ~~~~~~~
    at file:///berachain-experiments/utils.ts:48:7

    The expected type comes from property 'address' which is declared here on type 'ReadContractParameters<readonly [{ readonly type: "event"; readonly name: "Approval"; readonly inputs: readonly [{ readonly indexed: true; readonly name: "owner"; readonly type: "address"; }, { readonly indexed: true; readonly name: "spender"; readonly type: "address"; }, { ...; }]; }, ... 9 more ..., { ...; }], "sy...'
        address: Address;
        ~~~~~~~
        at file:///.cache/deno/npm/registry.npmjs.org/viem/2.22.16/_types/types/contract.d.ts:41:5

Found 4 errors.

error: Type checking failed.
```